import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import type { DiopsisConfig } from '../config.ts';
import type { Capture } from '../matrix.ts';

/** Absolute path of this package's compiled `dist` directory. */
export function distRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
}

export interface RunPlan {
  baseUrl: string;
  captures: PlannedCapture[];
  stabilize: DiopsisConfig['stabilize'];
  compare: DiopsisConfig['compare'];
  mask: string[];
  fullPage: boolean;
}

export interface PlannedCapture extends Capture {
  /** Unique, stable Playwright test title. */
  title: string;
  /** `toHaveScreenshot` path segments; joined by Playwright into `{arg}`. */
  segments: string[];
}

export interface GenerateOptions {
  /** Root of the project being tested. */
  root: string;
  config: DiopsisConfig;
  captures: Capture[];
  baseUrl: string;
  /** Absolute path of the reporter module, if one is being attached. */
  reporterPath?: string;
  /** Options handed to the reporter. */
  reporterOptions?: Record<string, unknown>;
}

export interface GeneratedProject {
  dir: string;
  configPath: string;
  planPath: string;
  cleanup(): Promise<void>;
}

export function planCaptures(captures: Capture[]): PlannedCapture[] {
  return captures.map((capture) => ({
    ...capture,
    title: `${capture.storyId} @${capture.width}`,
    segments: capture.snapshotPath.split('/'),
  }));
}

/**
 * The generated project lives under the tested project's `node_modules`, not the OS temp
 * directory, so that `@playwright/test` resolves by the ordinary upward lookup. Node's module
 * resolution skips ancestors already named `node_modules`, which puts the project's own
 * `node_modules` on the search path from here.
 */
export function projectDir(root: string): string {
  return path.join(root, 'node_modules', '.diopsis', 'project');
}

export async function generateProject(options: GenerateOptions): Promise<GeneratedProject> {
  const { root, config, baseUrl } = options;
  const dir = projectDir(root);
  await rm(dir, { recursive: true, force: true });
  await mkdir(dir, { recursive: true });

  const snapshotDir = path.resolve(root, config.snapshotDir);
  const outputDir = path.resolve(root, config.outputDir);
  const runtimeUrl = pathToFileURL(path.join(distRoot(), 'runtime', 'capture.js')).href;

  const plan: RunPlan = {
    baseUrl,
    captures: planCaptures(options.captures),
    stabilize: config.stabilize,
    compare: config.compare,
    mask: config.mask,
    fullPage: config.fullPage,
  };

  const planPath = path.join(dir, 'plan.json');
  await writeFile(planPath, JSON.stringify(plan, null, 2), 'utf8');

  // `type: module` so the generated `.js` files are ESM regardless of the host project.
  await writeFile(path.join(dir, 'package.json'), JSON.stringify({ type: 'module' }, null, 2), 'utf8');

  await writeFile(path.join(dir, 'diopsis.spec.js'), specSource(runtimeUrl), 'utf8');

  // `dot` for progress; the summary a reviewer reads comes from the Diopsis reporter.
  const reporters: string[] = [`['dot']`];
  if (options.reporterPath) {
    reporters.push(
      `[${JSON.stringify(options.reporterPath)}, ${JSON.stringify(options.reporterOptions ?? {})}]`,
    );
  }

  const configSource = `// Generated by Diopsis. Rewritten on every run; edits are lost.
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: ${JSON.stringify(dir)},
  outputDir: ${JSON.stringify(path.join(outputDir, 'test-results'))},
  fullyParallel: true,
  forbidOnly: false,
  retries: 0,
  ${config.workers === undefined ? '' : `workers: ${config.workers},\n  `}timeout: ${config.timeout},
  reporter: [${reporters.join(', ')}],
  snapshotPathTemplate: ${JSON.stringify(path.join(snapshotDir, '{arg}{ext}'))},
  use: {
    baseURL: ${JSON.stringify(baseUrl)},
    deviceScaleFactor: 1,
    colorScheme: 'light',
    // Locale and timezone are pinned for the same reason the clock is frozen: they change
    // rendered text, and a machine-dependent default makes a baseline machine-dependent.
    locale: 'en-US',
    timezoneId: 'UTC',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'], deviceScaleFactor: 1 } }],
});
`;

  const configPath = path.join(dir, 'playwright.config.js');
  await writeFile(configPath, configSource, 'utf8');

  return {
    dir,
    configPath,
    planPath,
    cleanup: () => rm(dir, { recursive: true, force: true }),
  };
}

function specSource(runtimeUrl: string): string {
  return `// Generated by Diopsis. Rewritten on every run; edits are lost.
import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import { openStory, storyUrlFor } from ${JSON.stringify(runtimeUrl)};

const plan = JSON.parse(readFileSync(new URL('./plan.json', import.meta.url), 'utf8'));

test.describe.configure({ mode: 'parallel' });

for (const capture of plan.captures) {
  test(capture.title, async ({ page }) => {
    await page.setViewportSize({ width: capture.width, height: capture.height });
    await openStory(page, storyUrlFor(plan.baseUrl, capture.storyId), plan.stabilize);

    await expect(page).toHaveScreenshot(capture.segments, {
      fullPage: plan.fullPage,
      animations: plan.stabilize.disableAnimations ? 'disabled' : 'allow',
      caret: 'hide',
      scale: 'css',
      mask: plan.mask.map((selector) => page.locator(selector)),
      maskColor: '#ff00ff',
      threshold: plan.compare.threshold,
      maxDiffPixelRatio: plan.compare.maxDiffPixelRatio,
    });
  });
}
`;
}
